"""adiciona disponivel em alimento

Revision ID: 25e6120e5580
Revises: e42be64a2a50
Create Date: 2026-08-21 17:12:16.880657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e6120e5580'
down_revision: Union[str, Sequence[str], None] = 'e42be64a2a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alimento', sa.Column('disponivel', sa.Boolean(), nullable=False))
    op.drop_column('categoria_alimento', 'ativo')
    op.drop_column('categoria_alimento', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria_alimento', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categoria_alimento', sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('alimento', 'disponivel')
    # ### end Alembic commands ###
