"""schema inicial

Revision ID: 3f332ba27c04
Revises: 
Create Date: 2026-08-19 00:27:03.573346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f332ba27c04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('forma_pagamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('restaurante',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('status_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('categoria_alimento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'nome')
    )
    op.create_table('endereco_cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('rua', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=5), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('ponto_de_referencia', sa.String(length=150), nullable=True),
    sa.Column('endereco_principal', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_admin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("papel IN ('admin','atendente','caixa','entregador')", name='ck_usuario_admin_papel'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('alimento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco_base >= 0', name='ck_alimento_preco_base_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_alimento.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardapio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario_admin.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'data')
    )
    op.create_table('fechamento_caixa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('total_vendas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_dinheiro', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_debito', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_credito', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_pedidos', sa.Integer(), nullable=False),
    sa.Column('quantidade_cancelados', sa.Integer(), nullable=False),
    sa.Column('valor_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_informado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diferenca', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fechado_por', sa.Uuid(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_fechamento_periodo_valido'),
    sa.ForeignKeyConstraint(['fechado_por'], ['usuario_admin.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=30), nullable=False),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_auditoria_entidade', 'log_auditoria', ['entidade', 'entidade_id'], unique=False)
    op.create_table('cardapio_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cardapio_id', sa.Uuid(), nullable=False),
    sa.Column('alimento_id', sa.Uuid(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('preco_dia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('preco_dia IS NULL OR preco_dia >= 0', name='ck_cardapio_item_preco_dia'),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimento.id'], ),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardapio_id', 'alimento_id')
    )
    op.create_index('idx_cardapio_item_disponivel', 'cardapio_item', ['cardapio_id', 'disponivel'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_pedido', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Uuid(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('endereco_nome', sa.String(length=150), nullable=False),
    sa.Column('endereco_telefone', sa.String(length=20), nullable=False),
    sa.Column('endereco_rua', sa.String(length=150), nullable=False),
    sa.Column('endereco_numero', sa.String(length=20), nullable=False),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=False),
    sa.Column('endereco_complemento', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('valor_itens', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_entrega', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago_dinheiro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_troco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fechamento_caixa_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_entrega >= 0', name='ck_pedido_valor_entrega'),
    sa.CheckConstraint('valor_itens >= 0', name='ck_pedido_valor_itens'),
    sa.CheckConstraint('valor_pago_dinheiro IS NULL OR valor_pago_dinheiro >= 0', name='ck_pedido_valor_pago_dinheiro'),
    sa.CheckConstraint('valor_total >= 0', name='ck_pedido_valor_total'),
    sa.CheckConstraint('valor_troco IS NULL OR valor_troco >= 0', name='ck_pedido_valor_troco'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['fechamento_caixa_id'], ['fechamento_caixa.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_index('idx_pedido_cliente', 'pedido', ['cliente_id'], unique=False)
    op.create_index('idx_pedido_data_hora', 'pedido', ['data_hora'], unique=False)
    op.create_index('idx_pedido_forma_pagamento', 'pedido', ['forma_pagamento_id'], unique=False)
    op.create_index('idx_pedido_restaurante_data_status', 'pedido', ['restaurante_id', 'data_hora', 'status_id'], unique=False)
    op.create_index('idx_pedido_status', 'pedido', ['status_id'], unique=False)
    op.create_table('historico_status_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('status_anterior_id', sa.Uuid(), nullable=True),
    sa.Column('status_novo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_anterior_id'], ['status_pedido.id'], ),
    sa.ForeignKeyConstraint(['status_novo_id'], ['status_pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historico_status_pedido', 'historico_status_pedido', ['pedido_id', 'alterado_em'], unique=False)
    op.create_table('pedido_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('alimento_id', sa.Uuid(), nullable=False),
    sa.Column('nome_alimento', sa.String(length=120), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('preco_unitario >= 0', name='ck_pedido_item_preco_unitario'),
    sa.CheckConstraint('quantidade > 0', name='ck_pedido_item_quantidade'),
    sa.CheckConstraint('subtotal >= 0', name='ck_pedido_item_subtotal'),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimento.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_item')
    op.drop_index('idx_historico_status_pedido', table_name='historico_status_pedido')
    op.drop_table('historico_status_pedido')
    op.drop_index('idx_pedido_status', table_name='pedido')
    op.drop_index('idx_pedido_restaurante_data_status', table_name='pedido')
    op.drop_index('idx_pedido_forma_pagamento', table_name='pedido')
    op.drop_index('idx_pedido_data_hora', table_name='pedido')
    op.drop_index('idx_pedido_cliente', table_name='pedido')
    op.drop_table('pedido')
    op.drop_index('idx_cardapio_item_disponivel', table_name='cardapio_item')
    op.drop_table('cardapio_item')
    op.drop_index('idx_log_auditoria_entidade', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_table('fechamento_caixa')
    op.drop_table('cardapio')
    op.drop_table('alimento')
    op.drop_table('usuario_admin')
    op.drop_table('endereco_cliente')
    op.drop_table('categoria_alimento')
    op.drop_table('status_pedido')
    op.drop_table('restaurante')
    op.drop_table('forma_pagamento')
    op.drop_table('cliente')
    # ### end Alembic commands ###
