"""add senha ao cliente

Revision ID: 7d2e5abb343e
Revises: 6f84bccec224
Create Date: 2026-08-24 21:56:09.528043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2e5abb343e'
down_revision: Union[str, Sequence[str], None] = '6f84bccec224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'senha_hash')
    # ### end Alembic commands ###
