"""remove cash_closing_id from order

Revision ID: a81b5cb13411
Revises: bef05f7919ed
Create Date: 2026-08-26 18:49:06.825080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81b5cb13411'
down_revision: Union[str, Sequence[str], None] = 'bef05f7919ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pedido_fechamento_caixa_id_fkey'), 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'fechamento_caixa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('fechamento_caixa_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pedido_fechamento_caixa_id_fkey'), 'pedido', 'fechamento_caixa', ['fechamento_caixa_id'], ['id'])
    # ### end Alembic commands ###
