"""adiciona conta de recebimento

Revision ID: bcb1810fd286
Revises: e40c3be370e8
Create Date: 2026-09-11 14:23:29.206097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb1810fd286'
down_revision: Union[str, Sequence[str], None] = 'e40c3be370e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta_recebimento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chave_pix', sa.String(length=140), nullable=False),
    sa.Column('tipo_chave_pix', sa.String(length=20), nullable=False),
    sa.Column('titular', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta_recebimento')
    # ### end Alembic commands ###
