"""add cash closing extra totals and order status is_paid

Revision ID: bef05f7919ed
Revises: ca5b601cc39d
Create Date: 2026-08-26 18:39:44.255000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef05f7919ed'
down_revision: Union[str, Sequence[str], None] = 'ca5b601cc39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('fechamento_caixa', sa.Column('total_outros', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('fechamento_caixa', sa.Column('total_dinheiro_recebido', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('fechamento_caixa', sa.Column('total_troco', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_fechamento_restaurante_periodo', 'fechamento_caixa', ['restaurante_id', 'data_inicio', 'data_fim'])
    op.add_column('status_pedido', sa.Column('pago', sa.Boolean(), nullable=False, server_default='false'))

    # marca o status ENTREGUE como pago=True (dado, não estrutura — autogenerate não detecta isso sozinho)
    status_pedido = sa.table(
        "status_pedido",
        sa.column("codigo", sa.String),
        sa.column("pago", sa.Boolean),
    )
    op.execute(
        status_pedido.update().where(status_pedido.c.codigo == "ENTREGUE").values(pago=True)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status_pedido', 'pago')
    op.drop_constraint('uq_fechamento_restaurante_periodo', 'fechamento_caixa', type_='unique')
    op.drop_column('fechamento_caixa', 'total_troco')
    op.drop_column('fechamento_caixa', 'total_dinheiro_recebido')
    op.drop_column('fechamento_caixa', 'total_outros')
    # ### end Alembic commands ###
