"""adiciona coordenadas e regras de frete

Revision ID: e40c3be370e8
Revises: c7b05e185f8d
Create Date: 2026-08-30 21:30:32.673891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40c3be370e8'
down_revision: Union[str, Sequence[str], None] = 'c7b05e185f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('min_distance_km', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_distance_km', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('endereco_cliente', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('endereco_cliente', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('restaurante', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('restaurante', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurante', 'longitude')
    op.drop_column('restaurante', 'latitude')
    op.drop_column('endereco_cliente', 'longitude')
    op.drop_column('endereco_cliente', 'latitude')
    op.drop_table('delivery_rules')
    # ### end Alembic commands ###
