"""adiciona descricao e ativo em categoria_alimento

Revision ID: e42be64a2a50
Revises: 48cc826cb81a
Create Date: 2026-08-21 08:49:28.600155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42be64a2a50'
down_revision: Union[str, Sequence[str], None] = '48cc826cb81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria_alimento', sa.Column('descricao', sa.Text(), nullable=True))
    op.add_column('categoria_alimento', sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria_alimento', 'ativo')
    op.drop_column('categoria_alimento', 'descricao')
    # ### end Alembic commands ###
